server:
  port: 8082


eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: Notification Service
  mail:
    host: localhost
    port: 1025
    username: ashutosh
    password: mailpassword
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            trust: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      group-id: notifier
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: ashu
    password: p@ssword
    hikari:
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true


